In [2]:
int(10)

10

In [3]:
import numpy as np



In [4]:
d1=np.array([1,23,45,67])
d1

array([ 1, 23, 45, 67])

In [6]:
d1.shape

(4,)

In [7]:
d1.size

4

In [8]:
d1[3]

67

In [9]:
d1[0:2]

array([ 1, 23])

In [10]:
data=np.array(["pravalli",23,10.25])
data

array(['pravalli', '23', '10.25'], dtype='<U8')

In [11]:
import time
start_time= time.time()
list1=[x for x in range(1,100000)]
list2=[y for y in range(1,100000)]
op=list(map(lambda x,y:x*y,list1,list2))
end_time=time.time()
print("time taken by list concept",end_time-start_time)

time taken by list concept 0.015625476837158203


In [12]:
import time
start_time1=time.time()
ar1=np.array(list1)
ar2=np.array(list2)
ar1*ar2
end_time=time.time()
print("time taken by list concept",end_time-start_time)


time taken by list concept 273.87490916252136


In [16]:
d2=np.array([[34,45,56,67],[45,89,78,76],[65,54,43,32]])
d2

array([[34, 45, 56, 67],
       [45, 89, 78, 76],
       [65, 54, 43, 32]])

In [17]:
d2[0]


array([34, 45, 56, 67])

In [18]:
d2[0][3]

67

In [20]:
d2[2].max()

65

In [21]:
d2[:,1].max()

89

In [22]:
d2[:,0].sum()

144

In [23]:
d2.sum(axis=0)

array([144, 188, 177, 175])

In [29]:
n=10
for i in range(1,n+1):
    print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 

In [31]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [33]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [34]:
print(np.zeros([2,3]))

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.tile(9,[2,3])

array([[9, 9, 9],
       [9, 9, 9]])

In [41]:
m=np.array([[1,2,3],[3,4,5],[455,566,567]])
m

array([[  1,   2,   3],
       [  3,   4,   5],
       [455, 566, 567]])

In [42]:
np.linalg.inv(m)

array([[-2.55454545,  2.56363636, -0.00909091],
       [ 2.60909091, -3.62727273,  0.01818182],
       [-0.55454545,  1.56363636, -0.00909091]])

In [43]:
np.random.random(10)

array([0.17858056, 0.28759985, 0.6064523 , 0.06518136, 0.21572724,
       0.59904867, 0.75746469, 0.82478061, 0.21845248, 0.55150478])

In [44]:
np.random

<module 'numpy.random' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [46]:
np.random.random(11)

array([0.03687269, 0.28341292, 0.09962739, 0.26762766, 0.91089521,
       0.86121121, 0.82167588, 0.46786829, 0.35672067, 0.00760401,
       0.10760667])

In [47]:
np.random.randint(10)

8

In [48]:
np.random.randint(10,20,30)

array([15, 11, 13, 16, 17, 11, 14, 15, 14, 16, 17, 19, 17, 11, 17, 18, 16,
       19, 19, 15, 13, 16, 16, 10, 17, 17, 10, 15, 12, 16])

In [49]:
np.random.rand(10)

array([0.13251333, 0.90576172, 0.77456413, 0.65268071, 0.76974943,
       0.93227105, 0.04079013, 0.72604638, 0.94852664, 0.23330543])

In [50]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [51]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [2]:
sec2=np.array(np.random.randint(10,20,[4,4]))
sec2

array([[14, 19, 19, 15],
       [19, 18, 13, 16],
       [13, 17, 16, 10],
       [14, 18, 15, 14]])

In [3]:
sec1=np.array(np.random.randint(10,20,[4,4]))
sec1

array([[12, 16, 19, 12],
       [15, 16, 19, 15],
       [17, 15, 18, 19],
       [19, 12, 19, 15]])

In [5]:
np.column_stack(sec1)

array([[12, 15, 17, 19],
       [16, 16, 15, 12],
       [19, 19, 18, 19],
       [12, 15, 19, 15]])

In [6]:
sec1*sec2

array([[168, 304, 361, 180],
       [285, 288, 247, 240],
       [221, 255, 288, 190],
       [266, 216, 285, 210]])

In [7]:
sec1.dot(sec2)

array([[ 887, 1055,  920,  794],
       [ 971, 1166, 1022,  881],
       [1023, 1241, 1091,  941],
       [ 951, 1170, 1046,  877]])

In [8]:
sec1@sec2

array([[ 887, 1055,  920,  794],
       [ 971, 1166, 1022,  881],
       [1023, 1241, 1091,  941],
       [ 951, 1170, 1046,  877]])

In [9]:
sec1.transpose()

array([[12, 15, 17, 19],
       [16, 16, 15, 12],
       [19, 19, 18, 19],
       [12, 15, 19, 15]])

In [10]:
sec1.trace()

61

In [13]:
np.hsplit(sec1,2)

[array([[12, 16],
        [15, 16],
        [17, 15],
        [19, 12]]), array([[19, 12],
        [19, 15],
        [18, 19],
        [19, 15]])]

In [14]:
np.hsplit(sec1,[2,2])

[array([[12, 16],
        [15, 16],
        [17, 15],
        [19, 12]]), array([], shape=(4, 0), dtype=int32), array([[19, 12],
        [19, 15],
        [18, 19],
        [19, 15]])]

In [15]:
np.vsplit(sec1,2)

[array([[12, 16, 19, 12],
        [15, 16, 19, 15]]), array([[17, 15, 18, 19],
        [19, 12, 19, 15]])]

In [16]:
np.abs(100.25)

100.25

In [17]:
np.abs(-199)

199

In [18]:
np.hsplit(sec1,1)

[array([[12, 16, 19, 12],
        [15, 16, 19, 15],
        [17, 15, 18, 19],
        [19, 12, 19, 15]])]

In [20]:
np.hsplit(sec1,2)

[array([[12, 16],
        [15, 16],
        [17, 15],
        [19, 12]]), array([[19, 12],
        [19, 15],
        [18, 19],
        [19, 15]])]

In [21]:
np.all(sec1>0)

True

In [22]:
np.floor(1213.4)

1213.0

In [23]:
np.ceil(122.13)

123.0